apiVersion: v2
description: Inofficial helm chart for code-server
home: https://konkube.github.io/helm-charts/
maintainers:
- email: info.konkube@gmail.com
  name: KonKube
name: codeserver
version: 1.0.0
appVersion: 202110
sources:
  - https://github.com/KonKube/codeserver_chart