{{- if not .Values.encryptedSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "codeserver.fullname" . }}
  labels: {{ include "codeserver.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ randAlphaNum 40 | b64enc | quote }}
{{- end }}